version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    open-pull-requests-limit: 1
    reviewers:
      - "shotaIDE"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    reviewers:
      - "shotaIDE"
    schedule:
      interval: "daily"
