name: "Setup Swift"
description: "Setup cache of Swift Package Manager"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
