name: CI

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  swift-lint:
    name: SwiftLint
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: SwiftLint
        run: swiftlint --strict
  swift-format:
    name: SwiftFormat
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: SwiftFormat
        run: swift package plugin --allow-writing-to-package-directory swiftformat --lint
  check-spell:
    name: Check spell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Install Code Spell Checker
        run: npm install -g cspell
      - name: Check Code Spell
        run: cspell . --config cspell.json . > cspell.log
      - name: Run reviewdog for Code Spell Checker
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat cspell.log | \
            reviewdog -efm='%f:%l:%c - %m' \
            -name='Code Spell Checker' \
            -reporter='github-pr-review'
