name: CI / iOS

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  swift-lint:
    name: SwiftLint
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: SwiftLint
        run: swiftlint --strict
  swift-format:
    name: SwiftFormat
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: SwiftFormat
        run: swift package plugin --allow-writing-to-package-directory swiftformat --lint
